-- 2024.04.02

-- 테이블 컬럼 > java 코드로
select 'private '
|| case
    when COL.DATA_TYPE = 'DATE' then 'String '
    when COL.DATA_TYPE = 'NUMBER' then 'Long '
    else 'String '
    end
|| FN_SNAKETOCAMEL(COL.COLUMN_NAME) || '; '
|| '// ' || UCC.COMMENTS
FROM COLS COL
INNER JOIN USER_COL_COMMENTS UCC 
    ON (COL.TABLE_NAME = UCC.TABLE_NAME AND COL.COLUMN_NAME = UCC.COLUMN_NAME)
WHERE 1=1
AND COL.TABLE_NAME = 'BUYER';

-- 테이블 정보보기
desc prod;

-- 컬럼 코멘트 적용하기
-- COMMENT ON COLUMN PROD.PROD_ID IS '상품코드';
SELECT 
    'COMMENT ON COLUMN '
    || TABLE_NAME || '.' || COLUMN_NAME
    || ' IS ''''; '
FROM COLS
WHERE TABLE_NAME = 'PROD';

COMMENT ON COLUMN PROD.PROD_ID IS '상품코드'; 
COMMENT ON COLUMN PROD.PROD_NAME IS '상품명'; 
COMMENT ON COLUMN PROD.PROD_LGU IS '상품분류'; 
COMMENT ON COLUMN PROD.PROD_BUYER IS '거래처'; 
COMMENT ON COLUMN PROD.PROD_COST IS '구매가'; 
COMMENT ON COLUMN PROD.PROD_PRICE IS '판매가'; 
COMMENT ON COLUMN PROD.PROD_SALE IS '세일가'; 
COMMENT ON COLUMN PROD.PROD_OUTLINE IS '요약정보'; 
COMMENT ON COLUMN PROD.PROD_DETAIL IS '상세정보'; 
COMMENT ON COLUMN PROD.PROD_IMG IS '이미지'; 
COMMENT ON COLUMN PROD.PROD_TOTALSTOCK IS '총재고'; 
COMMENT ON COLUMN PROD.PROD_INSDATE IS '입고일'; 
COMMENT ON COLUMN PROD.PROD_PROPERSTOCK IS '적정재고'; 
COMMENT ON COLUMN PROD.PROD_SIZE IS '크기'; 
COMMENT ON COLUMN PROD.PROD_COLOR IS '색상'; 
COMMENT ON COLUMN PROD.PROD_DELIVERY IS '배송방법'; 
COMMENT ON COLUMN PROD.PROD_UNIT IS '단위'; 
COMMENT ON COLUMN PROD.PROD_QTYIN IS '입고량'; 
COMMENT ON COLUMN PROD.PROD_QTYSALE IS '출고량'; 
COMMENT ON COLUMN PROD.PROD_MILEAGE IS '마일리지'; 



-- SELECT PROD LIST
-- 상품코드, 거래처코드, 분류코드, 상품명, 구매가, 판매가, 마일리지, 입고일을 조회한다.
-- 자식을 기준으로 조회를 할땐 INNER JOIN이든 OUTER JOIN 이든 상관없다
SELECT
      PROD.PROD_ID
    , PROD.PROD_BUYER
    , PROD.PROD_LGU
    , PROD.PROD_NAME
    , PROD.PROD_COST
    , PROD.PROD_PRICE
    , PROD.PROD_MILEAGE
    , PROD.PROD_INSDATE
    , BUYER.BUYER_NAME
    , LPROD.LPROD_NM
FROM PROD
INNER JOIN BUYER ON (PROD.PROD_BUYER = BUYER.BUYER_ID)
INNER JOIN LPROD ON (PROD.PROD_LGU = LPROD.LPROD_GU)
;

-- 컬럼 코멘트 적용하기
SELECT 
    'COMMENT ON COLUMN '
    || TABLE_NAME || '.' || COLUMN_NAME
    || ' IS ''''; '
FROM COLS
WHERE TABLE_NAME = 'BUYER';

COMMENT ON COLUMN BUYER.BUYER_ID IS '거래처아이디'; 
COMMENT ON COLUMN BUYER.BUYER_NAME IS '거래처명'; 
COMMENT ON COLUMN BUYER.BUYER_LGU IS '거래처코드'; 
COMMENT ON COLUMN BUYER.BUYER_BANK IS '은행명'; 
COMMENT ON COLUMN BUYER.BUYER_BANKNO IS '계좌번호'; 
COMMENT ON COLUMN BUYER.BUYER_BANKNAME IS '예금주명'; 
COMMENT ON COLUMN BUYER.BUYER_ZIP IS '우편번호'; 
COMMENT ON COLUMN BUYER.BUYER_ADD1 IS '기본주소'; 
COMMENT ON COLUMN BUYER.BUYER_ADD2 IS '상세주소'; 
COMMENT ON COLUMN BUYER.BUYER_COMTEL IS '회사전화번호'; 
COMMENT ON COLUMN BUYER.BUYER_FAX IS '팩스번호'; 
COMMENT ON COLUMN BUYER.BUYER_MAIL IS '이메일'; 
COMMENT ON COLUMN BUYER.BUYER_CHARGER IS '담당자'; 
COMMENT ON COLUMN BUYER.BUYER_TELEXT IS '전화번호?'; 

-- 컬럼명 가져오기
SELECT 
', ' || COLS.TABLE_NAME || '.' || COLUMN_NAME
FROM COLS
WHERE 1=1
AND COLS.TABLE_NAME = 'LPROD';


-- 상품 정보 가져오기 , 모든 정보(PROD, BUYER, LPROD)
SELECT
      PROD.PROD_ID
    , PROD.PROD_NAME
    , PROD.PROD_LGU
    , PROD.PROD_BUYER
    , PROD.PROD_COST
    , PROD.PROD_PRICE
    , PROD.PROD_SALE
    , PROD.PROD_OUTLINE
    , PROD.PROD_DETAIL
    , PROD.PROD_IMG
    , PROD.PROD_TOTALSTOCK
    , PROD.PROD_INSDATE
    , PROD.PROD_PROPERSTOCK
    , PROD.PROD_SIZE
    , PROD.PROD_COLOR
    , PROD.PROD_DELIVERY
    , PROD.PROD_UNIT
    , PROD.PROD_QTYIN
    , PROD.PROD_QTYSALE
    , PROD.PROD_MILEAGE
    , BUYER.BUYER_ID
    , BUYER.BUYER_NAME
    , BUYER.BUYER_LGU
    , BUYER.BUYER_BANK
    , BUYER.BUYER_BANKNO
    , BUYER.BUYER_BANKNAME
    , BUYER.BUYER_ZIP
    , BUYER.BUYER_ADD1
    , BUYER.BUYER_ADD2
    , BUYER.BUYER_COMTEL
    , BUYER.BUYER_FAX
    , BUYER.BUYER_MAIL
    , BUYER.BUYER_CHARGER
    , BUYER.BUYER_TELEXT
    , LPROD.LPROD_ID
    , LPROD.LPROD_GU
    , LPROD.LPROD_NM
FROM PROD
INNER JOIN BUYER ON (PROD.PROD_BUYER = BUYER.BUYER_ID)
INNER JOIN LPROD ON (PROD.PROD_LGU = LPROD.LPROD_GU)
WHERE 1=1
AND PROD.PROD_ID = 'P101000003';

-- 바이어 목록 조회하기
-- 거래처아이디, 거래처명, 분류코드(분류명), 소재지, 담당자명, 전화번호
SELECT
      BUYER.BUYER_ID
    , BUYER.BUYER_NAME
    , BUYER.BUYER_LGU
    , BUYER.BUYER_ZIP
    , BUYER.BUYER_ADD1
    , BUYER.BUYER_ADD2
    , BUYER.BUYER_COMTEL
    , BUYER.BUYER_CHARGER
    , LPROD.LPROD_NM
FROM BUYER
INNER JOIN LPROD ON (BUYER.BUYER_LGU = LPROD.LPROD_GU);


-- 바이어 목록 조회하기
-- 거래처아이디, 거래처명, 분류코드(분류명), 소재지, 담당자명, 전화번호
--거래처와의 거래품목의 갯수 
SELECT
      BUYER.BUYER_ID
    , BUYER.BUYER_NAME
    , BUYER.BUYER_LGU
    , BUYER.BUYER_ZIP
    , BUYER.BUYER_ADD1
    , BUYER.BUYER_ADD2
    , BUYER.BUYER_COMTEL
    , BUYER.BUYER_CHARGER
    , LPROD.LPROD_NM
    , NVL(PROD_VIEW.PROD_COUNT, 0) PROD_COUNT
FROM BUYER
INNER JOIN LPROD ON (BUYER.BUYER_LGU = LPROD.LPROD_GU)
LEFT OUTER JOIN (
        SELECT 
            PROD_BUYER
            , COUNT(PROD_ID) PROD_COUNT
        FROM PROD
        GROUP BY PROD_BUYER
) PROD_VIEW ON (BUYER.BUYER_ID = PROD_VIEW.PROD_BUYER)
;

-- 거래처별 목록구하기
SELECT 
    COUNT(DISTINCT PROD_BUYER)
FROM PROD;

SELECT PROD_BUYER, COUNT(PROD_ID) PROD_COUNT
FROM PROD
GROUP BY PROD_BUYER;




-- 거래처 단일 정보, 분류명, 거래품목(상품코드, 상품명, 구매가, 판매가, 마일리지)
-- 컬럼명 가져오기
SELECT 
', ' || COLS.TABLE_NAME || '.' || COLS.COLUMN_NAME || ' /* ' || USER_COL_COMMENTS.COMMENTS || ' */'
FROM COLS
INNER JOIN USER_COL_COMMENTS 
ON (COLS.TABLE_NAME = USER_COL_COMMENTS.TABLE_NAME
AND COLS.COLUMN_NAME = USER_COL_COMMENTS.COLUMN_NAME)
WHERE 1=1
AND COLS.TABLE_NAME = 'PROD';


SELECT 
  BUYER.BUYER_ID /* 거래처아이디 */
, BUYER.BUYER_NAME /* 거래처명 */
, BUYER.BUYER_LGU /* 거래처코드 */
, BUYER.BUYER_BANK /* 은행명 */
, BUYER.BUYER_BANKNO /* 계좌번호 */
, BUYER.BUYER_BANKNAME /* 예금주명 */
, BUYER.BUYER_ZIP /* 우편번호 */
, BUYER.BUYER_ADD1 /* 기본주소 */
, BUYER.BUYER_ADD2 /* 상세주소 */
, BUYER.BUYER_COMTEL /* 회사전화번호 */
, BUYER.BUYER_FAX /* 팩스번호 */
, BUYER.BUYER_MAIL /* 이메일 */
, BUYER.BUYER_CHARGER /* 담당자 */
, BUYER.BUYER_TELEXT /* 전화번호? */
, LPROD.LPROD_ID /* 상품순번 */
, LPROD.LPROD_GU /* 상품분류코드 */
, LPROD.LPROD_NM /* 상품분류명 */
, PROD.PROD_ID /* 상품코드 */
, PROD.PROD_NAME /* 상품명 */
, PROD.PROD_LGU /* 상품분류 */
, PROD.PROD_BUYER /* 거래처 */
, PROD.PROD_COST /* 구매가 */
, PROD.PROD_PRICE /* 판매가 */
, PROD.PROD_SALE /* 세일가 */
, PROD.PROD_OUTLINE /* 요약정보 */
, PROD.PROD_DETAIL /* 상세정보 */
, PROD.PROD_IMG /* 이미지 */
, PROD.PROD_TOTALSTOCK /* 총재고 */
, PROD.PROD_INSDATE /* 입고일 */
, PROD.PROD_PROPERSTOCK /* 적정재고 */
, PROD.PROD_SIZE /* 크기 */
, PROD.PROD_COLOR /* 색상 */
, PROD.PROD_DELIVERY /* 배송방법 */
, PROD.PROD_UNIT /* 단위 */
, PROD.PROD_QTYIN /* 입고량 */
, PROD.PROD_QTYSALE /* 출고량 */
, PROD.PROD_MILEAGE /* 마일리지 */
FROM BUYER
INNER JOIN LPROD ON (BUYER.BUYER_LGU = LPROD.LPROD_GU)
LEFT OUTER JOIN PROD ON (BUYER.BUYER_ID = PROD.PROD_BUYER)
WHERE BUYER.BUYER_ID = 'P10102';

SELECT *
FROM BUYER 
WHERE BUYER_ID = 'P10102';

SELECT *
FROM LPROD
WHERE LPROD_GU = 'P101';

SELECT *
FROM PROD
WHERE PROD_BUYER = 'P10102';

-- 컬럼명 가져오기
SELECT 
', ' || COLS.TABLE_NAME || '.' || COLS.COLUMN_NAME || ' /* ' || USER_COL_COMMENTS.COMMENTS || ' */'
FROM COLS
INNER JOIN USER_COL_COMMENTS 
ON (COLS.TABLE_NAME = USER_COL_COMMENTS.TABLE_NAME
AND COLS.COLUMN_NAME = USER_COL_COMMENTS.COLUMN_NAME)
WHERE 1=1
AND COLS.TABLE_NAME = 'LPROD';

































